### PR TITLE
Add signatures to all stub files

### LINKED ISSUE #226: Add signatures to all stub files
I notice it is a recurring source of annoyance to me that I have to figure out the signatures myself. Not seeing any real benefit to omitting them, I propose to add them to all stub files.

I'm prepared to do this myself; I'm opening this issue in the hope of hearing your thoughts.

### PR DESCRIPTION
**Pull request by MatthijsBlom**
Fixes #226

### CODE REVIEW

**Review by emiel — APPROVED** [review]
Thanks @MatthijsBlom! I don't have much time for a thorough review but it looks fine to me. I was able to run the tests locally (./scripts/ci) and everything is green.

**Comment by emiel** [comment]
@ErikSchierboom : Can you have a look and merge when you get a chance? Thanks!

**Comment by emiel** [comment]
Ping @ErikSchierboom. :)

**Review by ErikSchierboom — APPROVED** [review]
Great!

**Pull request merged**
