### PR TITLE
Update pangram test to remove non-ASCII characters, closes #53

### LINKED ISSUE #53: Pangram test with non-ASCII characters
The readme says `The alphabet used is ASCII, and case insensitive, from 'a' to 'z'
inclusively.`
but there is a test
```purescript
    test "pangram with non ascii characters" do
      Assert.equal true $
        isPangram "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich."
```
If I understand the task this test is invalid.

### PR DESCRIPTION
**Pull request by icyrockcom**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I haven't checked but _if_ this mimics a test from the canonical data (<https://github.com/exercism/problem-specifications/blob/f375051787370bd1af1dd84e8d6c116f07d88ad2/exercises/pangram/canonical-data.json>), then the `tests.toml` file should be updated to: <https://github.com/exercism/purescript/blob/3d0913a2f4463adeb85c4c7847eb2e0f510c1038/exercises/practice/pangram/.meta/tests.toml>.

Can you confirm it's either not necessary (because it doesn't exist in the canonical data) or update it, either manually, or by using `configlet`?

**Comment by icyrockcom** [comment]
@SleeplessByte This particular test is already there:

https://github.com/exercism/problem-specifications/blob/main/exercises/pangram/canonical-data.json#L90

https://github.com/exercism/purescript/blob/3d0913a2f4463adeb85c4c7847eb2e0f510c1038/exercises/practice/pangram/.meta/tests.toml#L39

**Comment by icyrockcom** [comment]
The descriptions do not match though and there's one more test in the problem set:

```
    test "sentence empty" do
    test "pangram with only lower case" do
    test "missing character 'x'" do
    test "another missing character 'x'" do
    test "pangram with underscores" do
    test "pangram with numbers" do
    test "missing letters replaced by numbers" do
    test "pangram with mixed case and punctuation" do
    test "upper and lower case versions of the same character should not be counted separately" do
```

vs

```
# - Recreate every `description` key/value pair
description = "empty sentence"
description = "perfect lower case"
description = "only lower case"
description = "missing the letter 'x'"
description = "missing the letter 'h'"
description = "with underscores"
description = "with numbers"
description = "missing letters replaced by numbers"
description = "mixed case and punctuation"
description = "case insensitive"
```

Do you want me to update that before you merge?

**Comment by SleeplessByte** [comment]
That would be grand if you could!

**Comment by icyrockcom** [comment]
@SleeplessByte Done, let me know how it looks.

**Review by SleeplessByte — APPROVED** [review]
This looks great. Let's do it. Erik can comment tomorrow if he wants, but yay!

**Comment by SleeplessByte** [comment]
Your change will be live in a few minutes on <https://exercism.org/>. Sign up with GitHub if you don't have an account yet!

**Pull request merged**
