### PR TITLE
Pangram test with non-ASCII characters, closes #53

### LINKED ISSUE #53: Pangram test with non-ASCII characters
The readme says `The alphabet used is ASCII, and case insensitive, from 'a' to 'z'
inclusively.`
but there is a test
```purescript
    test "pangram with non ascii characters" do
      Assert.equal true $
        isPangram "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich."
```
If I understand the task this test is invalid.

### PR DESCRIPTION
**Pull request by icyrockcom**
Update for https://github.com/exercism/purescript/issues/53 to remove non-ASCII test and sync up with canonical data:

https://github.com/exercism/problem-specifications/blob/f375051787370bd1af1dd84e8d6c116f07d88ad2/exercises/pangram/canonical-data.json

### CODE REVIEW

**Comment by chuckwondo** [comment]
@icyrockcom Is there any reason you deleted your `icyrockcom:pangram-non-ascii` branch? I recently started the PureScript track and ran into this issue. As far as I can tell from the various related issues, it appears that it was agreed that the "non-ASCII" test should be removed. Can we reopen this and get your changes approved?

**Comment by icyrockcom** [comment]
@chuckwondo Not intentional :) I was cleaning up branches recently when I started working on a couple more things. I've restored the branch in case others think it's a good idea to have it merged.

**Comment by chuckwondo** [comment]
@lpil I don't know what the protocol is for this, but since you're the author of this exercise, I'm reaching out to you to see how we can get this reviewed and merged.

**Comment by lpil** [comment]
Hi @chuckwondo , I'm afraid I am not a maintainer of this track any more.

**Comment by SleeplessByte** [comment]
This can't be reopened because the master branch has been renamed. It has to be "recreated".

@ErikSchierboom and I can then look at it and have it merged.

**Comment by icyrockcom** [comment]
Thanks @SleeplessByte see https://github.com/exercism/purescript/pull/218

**Pull request closed without merging**
