### PR TITLE
Port to spago from bower/pulp

### PR DESCRIPTION
**Pull request by emiel**
Here is my attempt to continue with the work done here #127 in replacing bower/pulp with spago. I focused on getting CI setup to build and test the concept and practice exercises. The approach is more or less similar to what was being done for bower. A spago project uses two files `packages.dhall` (defines package-set) and `spago.dhall` (project dependencies) for CI all exercises are built and tested using the same package set so that we can share the spago package cache (.spago) and build artifacts (output).

We gain some additional flexibility in that spago.dhall can now vary per exercise. This is nice because we can whittle down the exercise dependencies to the bare minimum and we save students some disk space. Also PureScript 0.14.x has started warning about unused dependencies... a topic for when we tackle porting the exercises to 0.14.x.

Work on updating the related documentation will follow in another PR as there is now quite some overlap with the official Exercism documentation and I'd like things to settle a bit a bit before tackling the docs. I expect there to be more changes as we migrate to PureScript 0.14.x especially in how we deal with dependencies.

Let me know if you have any questions. ;)

### CODE REVIEW

**Comment by emiel** [comment]
As mentioned before the test-runner also needs to support spago and there is a PR here (https://github.com/exercism/purescript-test-runner/pull/8). The test-runner pre-compiles the package dependencies and I've come back and taken a similar approach here.

For those following along this is a simpler approach than my previous PR and I'm happy to be using a shell script over nodejs. ;)

**Comment by ErikSchierboom** [comment]
I'll let @aimorris look into this, but it looks good to me!

**Review by aimorris — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Want me to squash or rebase @emiel?

**Comment by emiel** [comment]
Thanks for reviewing @ErikSchierboom and @aimorris! Please go ahead and **rebase** because I believe the commits are easy enough to follow. The first commit add a bunch of boilerplate (exercise configuration) which would make a single commit difficult to navigate.

**Comment by ErikSchierboom** [comment]
@emiel Done! Thanks a lot

**Pull request merged**
