### PR TITLE
Upgrade to PureScript 0.14.3 and add / update docs, remove references to bower 

### PR DESCRIPTION
**Pull request by icyrockcom**

### CODE REVIEW

**Comment by iHiD** [comment]
(cc @emiel)

**Review by emiel — COMMENTED** [review]
Thanks for the PR!

A few general points.

* Preferably I'd like to see a PR per topic. Here we are mixing up a couple of unrelated changes. It makes it easier to give more directed feedback and we can pick and choose much easier (this goes in; this does not). I know when you're in the groove we tend to skip over this and changes get bunched together. ;)

* Before this can be merged the `purescript-test-runner` needs to be updated as well. The solutions are run in a sand-box (Docker) with no network connectivity. Everything required to build and test the solution must be in the Docker image. I've made a start here: https://github.com/emiel/purescript-test-runner/tree/emiel-purescript-0.14

* I'm not too familiar with configlet. It is generally run by CI but can be run locally as well. The `bin/fetch-configlet` script fetches the latest version. I'm not sure what is expected by Exercism developers here. It doesn't hurt to keep it I guess. Perhaps @ErikSchierboom can chime in here.

* I noticed the solution exercise dependencies were updated as well. This is an issue I was still on the fence about. See https://github.com/exercism/purescript/issues/186. There is the web interface but there is also still the CLI. With the CLI users would download a bunch of dependencies they would not actually need. Another thing that needs to happen is that the dependencies need to be kept in sync with what is available by the purescript-test-runner. This change adds dependencies which are not available under purescript-test-runner at the moment. We just need to make a call here on what works best. Ideally we would setup CI to build all the exercise solutions so we know when a dependency is out of sync. I do this manually at the moment.

That is all I have time for at the moment. :/ Nice job so far!

**Comment by icyrockcom** [comment]
@emiel Thanks!

1. I'll close this PR and submit 3 separate PRs, so we discuss them one by one
2. I'll look at `purescript-test-runner` and discuss in its repository as needed
3. I'll restore `bin/fetch-configlet`
4. Let me know how you'd like me to proceed regarding this if not the way I did it

**Comment by ErikSchierboom** [comment]
> I'm not too familiar with configlet. It is generally run by CI but can be run locally as well. The bin/fetch-configlet script fetches the latest version. I'm not sure what is expected by Exercism developers here. It doesn't hurt to keep it I guess. Perhaps @ErikSchierboom can chime in her

configlet is indeed also intended to be run locally, as it not only has linting functionality but also syncing functionality that one runs locally to update the repo.

**Comment by ErikSchierboom** [comment]
> Before this can be merged the purescript-test-runner needs to be updated as well. 

Indeed, that is very important. Let me know if you need any help.

**Pull request closed without merging**
