### PR TITLE
Use spago instead of pulp and bower

### LINKED ISSUE #119: Bower Dependency
`npm` wont let me install bower

I am on Arch Linux with `npm version: 6.12.0`
It says that `bower` is deprecated.

Is there any way around this?
I tried to learn `elm`, but it is too painful coming from Haskell, so I really want to try `purescript`

### PR DESCRIPTION
**Pull request by connorads**
## Summary

This PR updates the PureScript docs and exercises to use `spago`.
Fixes #119

`spago` is now preferred over `bower` on PureScript [website](https://www.purescript.org/) and [getting started guide](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md#setting-up-the-development-environment).

## Todo

- [x] Update `INSTALLATION.md` and `TESTS.md`
- [x] Replace exercises `bower.json` with `packages.dhall` and `spago.dhall`
- [x] Update `.gitignore`
- [ ] Fix build break related to `check-bower.sh`
- [ ] Update other scripts
- [ ] Update `README.md`
- [ ] Update `.travis.yml`

## More info

Used `spago init` to migrate each exercise and then deleted the respective `bower.json`.
```
spago init   
[info] Initializing a sample project or migrating an existing one..
[info] Found a "bower.json" file, migrating to a new Spago config..
[info] All Bower dependencies are in the set! ?
[info] You can now safely delete your "bower.json"
[info] Updating package-set tag to "psc-0.13.8-20201223"    
Fetching the new one and generating hashes.. (this might take some time)
[info] Generating new hashes for the package set file so it will be cached.. (this might take some time)
[info] Found existing directory "src", skipping copy of sample sources 
[info] Found existing directory "test", skipping copy of sample sources
[info] Set up a local Spago project.
[info] Try running `spago build`
```

Then used `spago test` to install packages and run tests.
All the packages seemed to install and then the tests seem to fail as expected.
```
spago test
Compiling PascalsTriangle
Error found:
in module PascalsTriangle
at src\PascalsTriangle.purs:1:25 - 1:29 (line 1, column 25 - line 1, column 29)

  Cannot export unknown value rows


See https://github.com/purescript/documentation/blob/master/errors/UnknownExport.md for more information,
or to contribute content related to this error.


[error] Failed to build.
```

### CODE REVIEW

**Comment by guygastineau** [comment]
@connorads Do you want some extra fingers on this PR?

**Comment by connorads** [comment]
Yes, would love them!

**Comment by guygastineau** [comment]
Alright, I will try to find some time.  purescript did manage to piss me off a bit over the last hour lol (I just want it to be Haskell in the browser, and it is NOT that).  Still, I guess it is the closest I can get.

**Comment by emiel** [comment]
I'd also like to see this moving along and can spend some time on it. I'm curious who is able to merge these PRs...

**Comment by aimorris** [comment]
I can merge the PR once it's complete. I might be able to help out over the next week, or I might not.

**Comment by ErikSchierboom** [comment]
@emiel Is this superseded by https://github.com/exercism/purescript/pull/189 and can it be closed?

**Comment by emiel** [comment]
@ErikSchierboom : As far as I'm concerned everything in this PR is covered by the changes now in `main` (#189). There are some remaining "cleanup" items to take care of (updating the documentation, removing some leftovers, etc). Thanks to @connorads for the initial push!

- https://github.com/exercism/purescript/issues/202
- https://github.com/exercism/purescript/issues/193
- https://github.com/exercism/purescript/issues/186

**Pull request closed without merging**
