### PR TITLE
Also able to help maintain (and have a little in the past)

### PR DESCRIPTION
**Pull request by spicydonuts**

### CODE REVIEW

**Comment by mawis** [comment]
Sounds perfect to me. I happy to have someone to discuss things with and for review.
If you didn't do so already, I think you should ping kytrinyx/Katrina or ihid/Jeremy directly (e.g. on Slack), so that they see the pull request. It takes a little bit more than just accepting the pull request.

**Comment by mawis** [comment]
It seems nothing is going forward with this pull request. Have you contacted them?

As said, I don't know if purely merging this request would do anything but adding you to the list of maintainers on the website. I think you also have to get rights granted, so I would suggest you discuss this with @kytrinyx or @iHiD

**Comment by iHiD** [comment]
Merging the PR does all of the permissions stuff automatically (because of @kytrinyx dark-magic). But also, please do contact me on Slack so I can add you to the relevant channels etc.

@spicydonuts Is this something you're still interested in? :)

**Comment by spicydonuts** [comment]
Yep. I didn't really follow up because I'd done that a few months ago and didn't get a response. I'd like to help out though!

**Pull request merged**
